### ISSUE TITLE
有没有 结合 spring  的例子呀

### ISSUE THREAD

**Issue by liu212117** [biezhi/telegram-bot-api#1]
我在 spring 里面 启动 会报错   是怎么回事了  谢谢

**Comment by hellokaton** [comment]
和 `spring` 没有关系的，报错可能是你被墙了，国内玩这个不太好搞。。。

**Comment by hellokaton** [comment]
不过支持设置代理的，你如果有 `http` 的代理可以设置一下。
[这里](https://github.com/biezhi/telegram-bot-api/blob/master/src/test/java/io/github/biezhi/tgbot/TelegramBotTest.java#L36)是代码。
